### ISSUE TITLE
Project copyright

### ISSUE THREAD

**Issue by danielywang** [sha186/unitevolbiz#1]
@sha186,
This is a final copyright notice — you have ignored my last one. I own the source code that you copied and presented as your own (without any credit). Again, I am open to talking about a partnership, but as of now, you do not have permission to use or modify this code in any form. You are to delete this repository and you may not create new repositories on Github or use this code anywhere. Please notify your associates also. I hope this issue can stop here, but if you continue to disrespect my written communication or work, I will take legal action with DMCA.

-Daniel

**Comment by sha186** [comment]
sure i will delete the repository
